@arm = https://management.azure.com
@graph = https://graph.windows.net

@arm-cn = https://management.chinacloudapi.cn
@graph-cn = https://graph.chinacloudapi.cn

@arm-de = https://management.microsoftazure.de
@graph-de = https://graph.cloudapi.de

@arm-us = https://management.usgovcloudapi.net
@graph-us = https://graph.windows.net

@arm-ppe = https://api-dogfood.resources.windows-int.net
@graph-ppe = https://graph.ppe.windows.net

###
// Use the default directory for the account
GET {{arm}}/tenants?api-version=2017-08-01
Authorization: {{$aadToken}}
###
// Explicit directory using tenant ID
GET {{arm}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken f884863f-04ce-4326-b064-dfbc608f0dd2}}
###
// Restart Code to clear the token cache before continuing -- next 2 tests cover saving the tenant id when starting with a domain
###
// Explicit directory using domain name
GET {{arm}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken dreamsparkuser1outlook.onmicrosoft.com}}
###
// Explicit directory using tenant ID -- should reuse domain-based token
GET {{arm}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken f884863f-04ce-4326-b064-dfbc608f0dd2}}
###
// Do not reuse older token -- force re-authentication (e.g. switch account)
GET {{arm}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken new dreamsparkuser1outlook.onmicrosoft.com}}
###
// Implicit cloud selection (via REST endpoint TLD) -- cn
// TODO: FAILED!!!
GET {{arm-cn}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken}}
###
// Implicit cloud selection (via REST endpoint TLD) -- de
GET {{arm-de}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken}}
###
// Explicit cloud selection -- public
GET {{arm}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken public}}
###
// Explicit cloud selection -- cn
// TODO: FAILED!!!
GET {{arm-cn}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken new cn bbedd486-2c6a-4208-a2df-56f43cc823aa}}
###
// Explicit cloud selection -- de
GET {{arm-de}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken de}}
###
// Explicit cloud selection -- us
GET {{arm-us}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken us}}
###
// Explicit cloud selection -- ppe
GET {{arm-ppe}}/subscriptions?api-version=2017-08-01
Authorization: {{$aadToken ppe}}
###
// Explicit audience selection
GET {{graph}}/me?api-version=1.6
Authorization: {{$aadToken microsoft.com aud:https://management.core.windows.net/}}
###