<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>source.http</string>
        <key>fileTypes</key>
        <array>
            <string>http</string>
            <string>rest</string>
        </array>
        <key>keyEquivalent</key>
        <string>^~H</string>
        <key>name</key>
        <string>http</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>^\s*#.*$\n?</string>
                <key>name</key>
                <string>comment.source.sharp.http</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*//.*$\n?</string>
                <key>name</key>
                <string>comment.source.double-slash.http</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.http</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>const.language.http</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.http</string>
                    </dict>
                    <key>7</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.http</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>^(?:((?i)get|post|put|delete|patch|head|options|connect|trace(-?))\s+)?\s*(\S+)(?:\s+(((?i)HTTP(-?))\/(\S+)))?$</string>
                <key>name</key>
                <string>http.requestline</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>support.variable.http</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string.other.http</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>^([\w\-]+)\s*\:\s*(.*?)\s*</string>
                <key>name</key>
                <string>http.requestheaders</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.http</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.http</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.http</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.http</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>^\s*((?i)HTTP(-?))\/(\S+)\s([1-5][0-9][0-9])\s(.*)$</string>
                <key>name</key>
                <string>http.responseLine</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.http</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.http</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>string.other.http</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>^\s*(@)([^\s=]+)\s*=\s*(.+)\s*$</string>
                <key>name</key>
                <string>http.filevariable</string>
            </dict>
        </array>
    </dict>
</plist>